# Generated by Django 5.2.7 on 2025-10-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(default=37.47654440298837),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(default=126.95920363836325),
            preserve_default=False,
        ),
    ]
