# Generated by Django 5.2.7 on 2025-10-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_profile_business_doc_profile_naver_map_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller_id',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True),
        ),
    ]
